"""Add new table exchange

Revision ID: 26957ba5f737
Revises: a720fc00913a
Create Date: 2023-02-19 15:54:00.797560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26957ba5f737'
down_revision = 'a720fc00913a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('accepted_date', sa.DateTime(), nullable=True),
    sa.Column('rejected_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange')
    # ### end Alembic commands ###

