"""change model exchange

Revision ID: d81985209635
Revises: 26957ba5f737
Create Date: 2023-02-20 11:45:40.349700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81985209635'
down_revision = '26957ba5f737'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('rejected_date')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###

